name: deploy_to_test

concurrency: 1

on:
  workflow_dispatch

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID}}

jobs:
  deploy:
    environment: test
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle validate -t "test" --var="env=test"
        working-directory: .

      - run: databricks bundle deploy -t "test" --var="env=test"
        working-directoy: .